/**
 * Drops MDX comments (`{/* … *\/}`) from the mdast before anything serializes it.
 *
 * MDX comments render as nothing, so authors reasonably treat them as private —
 * `content/reference/pear/cli.mdx` carried a long maintainer note explaining how
 * to diff the CLI surface between tags, and every landing page carries editorial
 * notes about card ordering. None of that is reader-facing in the HTML.
 *
 * It was reader-facing in the Markdown, though. `postprocess.includeProcessedMarkdown`
 * serializes the mdast, and an `mdxFlowExpression` holding a comment survives that
 * serialization, so all of it was being written into the per-page `.md` files that
 * `Accept: text/markdown` and every LLM client fetch (`out/**\/*.md`, generated by
 * `scripts/generate-llm-md-files.ts`). Over twenty pages leaked notes this way,
 * including the maintainer note's own literal `[!version since=x.y.z]` example row
 * — which reads as a real row of `pear touch --help` output to anything consuming
 * the Markdown.
 *
 * Same reasoning as `remarkVersionCodeLines`: the fix has to be a remark pass,
 * because by the time rehype runs the Markdown has already been captured.
 *
 * Only comment-only expressions are removed. `{someExpression}` is left alone,
 * and so is `{/* a *\/ value}` — anything whose payload is not exclusively
 * comments still carries meaning.
 */

import type { Root } from 'mdast';
import { visit, CONTINUE, SKIP } from 'unist-util-visit';

/** Node types MDX uses for `{…}` payloads, at block and inline level. */
const EXPRESSION_TYPES = new Set(['mdxFlowExpression', 'mdxTextExpression']);

/** Whether `value` is nothing but `/* … *\/` comments and whitespace. */
function isCommentOnly(value: unknown): boolean {
  if (typeof value !== 'string') return false;
  // Strip every block comment, then see whether anything meaningful is left.
  const withoutComments = value.replace(/\/\*[\s\S]*?\*\//g, '');
  return value.trim().length > 0 && withoutComments.trim().length === 0;
}

export function remarkStripMdxComments() {
  return (root: Root) => {
    visit(root, (node, index, parent) => {
      if (!parent || index === undefined) return CONTINUE;
      if (!EXPRESSION_TYPES.has(node.type)) return CONTINUE;
      if (!isCommentOnly((node as { value?: unknown }).value)) return CONTINUE;

      parent.children.splice(index, 1);
      // The node at `index` is now the next sibling — revisit this position.
      return [SKIP, index];
    });
  };
}
