root: ./

redirects:
  "building-blocks/hypercore": "https://github.com/holepunchto/hypercore"
  "building-blocks/hyperbee": "https://github.com/holepunchto/hyperbee"
  "building-blocks/hyperdrive": "https://github.com/holepunchto/hyperdrive"
  "building-blocks/autobase": "https://github.com/holepunchto/autobase"
  "building-blocks/hyperdht": "https://github.com/holepunchto/hyperdht"
  "building-blocks/hyperswarm": "https://github.com/holepunchto/hyperswarm"
  "helpers/corestore": "https://github.com/holepunchto/corestore"
  "helpers/localdrive": "https://github.com/holepunchto/localdrive"
  "helpers/mirrordrive": "https://github.com/holepunchto/mirror-drive"
  "helpers/secretstream": "https://github.com/holepunchto/hyperswarm-secret-stream"
  "helpers/compact-encoding": "https://github.com/holepunchto/compact-encoding"
  "helpers/protomux": "https://github.com/holepunchto/protomux"
  "tools/hypershell": "https://github.com/holepunchto/hypershell"
  "tools/hypertele": "https://github.com/bitfinexcom/hypertele"
  "tools/hyperbeam": "https://github.com/holepunchto/hyperbeam"
  "tools/hyperssh": "https://github.com/holepunchto/hyperssh"
  "tools/drives": "https://github.com/holepunchto/drives"
