// scripts/bare-refgen/todo.ts
//
// Generates generated/bare-refs/TODO.md — the human-attention checklist for the
// current set of generated pages. Everything here needs a person, not the
// pipeline: modules with no author-written prose to draw from, auto-transcribed
// descriptions to review, and gaps the transcriber surfaced. Re-run after any
// gen/transcribe so the list stays current.
//
// Run: npm run bare-refs:todo

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { OUT_DIR, LAYOUTS_DIR, STABILITY, CATALOG_MDX, PREFIX } from './config';
import type { BareModel } from './model';

const OUT = join(OUT_DIR, 'TODO.md');

interface Suggested {
  describe: Record<string, string>;
  unmatchedHeadings: string[];
  undocumentedSymbols: string[];
}

async function main(): Promise<void> {
  const names = (await readdir(OUT_DIR, { withFileTypes: true }))
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const noProse: string[] = [];
  const needsReview: string[] = [];
  const gaps: string[] = [];
  const stabilityUnset: string[] = [];

  // Module names present in the family's catalog table (stability verified there).
  const catalogNames = new Set<string>();
  if (existsSync(CATALOG_MDX)) {
    const text = await readFile(CATALOG_MDX, 'utf8');
    const re = new RegExp(`\\[(${PREFIX}[a-z0-9-]+)\\]`, 'g');
    let m: RegExpExecArray | null;
    while ((m = re.exec(text)) !== null) catalogNames.add(m[1]);
  }

  for (const name of names) {
    const model = JSON.parse(await readFile(join(OUT_DIR, name, 'api-model.json'), 'utf8')) as BareModel;
    const hasDescribe = existsSync(resolve(LAYOUTS_DIR, `${name}.describe.json`));
    const exportCount = model.exports.length;

    if (!hasDescribe) {
      noProse.push(`- [ ] **${name}** — no author-written descriptions (no README \`## API\`). ${exportCount} exports render signatures-only. Needs upstream TSDoc or hand-authored prose. Do NOT auto-generate.`);
    } else {
      needsReview.push(`- [ ] **${name}** — review \`layouts/${name}.describe.json\` (auto-transcribed from the README; spot-check for mismatches/junk).`);
    }

    const sp = join(OUT_DIR, name, 'describe.suggested.json');
    if (existsSync(sp)) {
      const s = JSON.parse(await readFile(sp, 'utf8')) as Suggested;
      if (s.unmatchedHeadings.length || s.undocumentedSymbols.length) {
        gaps.push(
          `- [ ] **${name}** — ${s.unmatchedHeadings.length} README-only heading(s) (in README, absent from types — check for upstream \`.d.ts\` gaps or naming: ${s.unmatchedHeadings.slice(0, 8).join(', ') || '—'}); ${s.undocumentedSymbols.length} symbol(s) with no prose.`,
        );
      }
    }

    // Stability is verified when the module has an explicit STABILITY entry or
    // a catalog row (whose Stability column syncCatalog keeps authoritative).
    if (!(name in STABILITY) && !catalogNames.has(name)) stabilityUnset.push(name);
  }

  const skipPath = join(OUT_DIR, '_skipped.json');
  const skipped: string[] = existsSync(skipPath) ? JSON.parse(await readFile(skipPath, 'utf8')) : [];

  const catalogAddedPath = join(OUT_DIR, '_catalog-added.json');
  const catalogAdded: string[] = existsSync(catalogAddedPath) ? JSON.parse(await readFile(catalogAddedPath, 'utf8')) : [];

  const lines = [
    `# ${PREFIX}* references — human review TODO`,
    '',
    '_Auto-generated by the refgen todo script. Everything below needs a person._',
    '',
    '## Selected but not documented — ship no usable `.d.ts`',
    '',
    ...(skipped.length
      ? skipped.map((n) => `- [ ] **${n}** — in the top-N by downloads but the published package ships no \`.d.ts\` (or declares one it doesn\'t ship). Needs upstream types before it can be generated.`)
      : ['- _none_']),
    '',
    '## Modules with no author-written descriptions (mandate: do not fabricate)',
    '',
    ...(noProse.length ? noProse : ['- _none_']),
    '',
    '## Auto-transcribed descriptions to review before going live',
    '',
    ...(needsReview.length ? needsReview : ['- _none_']),
    '',
    '## Coverage gaps surfaced by the transcriber',
    '',
    ...(gaps.length ? gaps : ['- _none_']),
    '',
    '## Catalog rows auto-added — verify section placement',
    '',
    ...(catalogAdded.length
      ? catalogAdded.map((n) => `- [ ] **${n}** — had no catalog row; \`syncCatalog\` added one under the fallback section. Move it to the section that actually fits.`)
      : ['- _none_']),
    '',
    '## Stability to confirm',
    '',
    stabilityUnset.length
      ? `- [ ] Set/verify stability in \`config.ts\` STABILITY for: ${stabilityUnset.join(', ')} (defaulting to \`stable\`).`
      : '- _all set_',
    '',
    '## Before committing / going live',
    '',
    '- [ ] Render the generated pages in the Fumadocs dev server (compile-checked only so far).',
    '- [ ] Side-by-side a few against the existing hand-written pages.',
    '- [ ] Spot-check a source link resolves at its pinned version tag.',
    '',
  ];

  await writeFile(OUT, lines.join('\n'));
  console.log(`📝 Wrote ${OUT}: ${noProse.length} no-prose · ${needsReview.length} to review · ${gaps.length} with gaps.`);
}

main().catch((err) => {
  console.error('Error:', err);
  process.exit(1);
});
