// scripts/check-docs-versions.ts
//
// Validates the platform version-gating markers under content/ against the
// doc-states declared for whichever axis each page belongs to
// (src/lib/version-axes.ts) — Pear's four platform pages (DOCS_VERSIONS,
// hand-maintained) plus the three independent Bare axes (bare-cli,
// bare-runtime, bare-kit; each generated by scripts/gen-bare-docs-states.ts).
//
// Nothing else catches a wrong version string. The remark plugin rejects a
// malformed one at build time, but a WELL-FORMED version that is not a real
// doc-state — `since="3.2.0"` before 3.2 exists, or `since="3.10"` for a typo'd
// 3.1.0 — compiles to a gate whose `data-version-*` can never match any
// selectable option. The section then stays visible in every version with no
// error anywhere: the failure mode is silence, which is exactly what a check
// script is for. It also pins the invariants each axis's version list has to
// hold, which were previously enforced only by a comment.
//
// A marker on a page with NO registered axis is flagged too — that would mean
// a version dropdown's worth of content exists on a page with no dropdown to
// select it, which is exactly the false model the design forbids (a `bare-*`
// module page or any other reference page asserting it tracks a platform
// version it doesn't).
//
// Run as `npm run check:docs-versions`. Exit 0 on pass, 1 on any error.
import { readFile, readdir } from 'fs/promises';
import { join, relative } from 'path';
import { compareVersions } from '../src/lib/docs-versions';
import { VERSION_AXES, getVersionAxis, versionsNewestFirst, type VersionAxis } from '../src/lib/version-axes';
import { fileToSlug } from './helpers';

const CONTENT_DIR = 'content';

/**
 * Every way a version can be written into a page. Each pattern captures the
 * version in group 1, so one loop handles them all.
 */
const MARKERS: { what: string; re: RegExp }[] = [
  { what: '<VersionSection>', re: /<VersionSection\b[^>]*?\b(?:since|until)="([^"]*)"/g },
  { what: '<VersionGate>', re: /<VersionGate\b[^>]*?\b(?:since|until)="([^"]*)"/g },
  { what: '<Since>/<Until>', re: /<(?:Since|Until)\b[^>]*?\bv="([^"]*)"/g },
  { what: 'fence marker', re: /\[!version\s+(?:since|until)=([^\]\s]+)\]/g },
];

const VERSION_RE = /^\d+(\.\d+){0,2}$/;

interface Problem {
  file: string;
  line: number;
  what: string;
  version: string;
  reason: string;
}

async function findMdx(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await findMdx(path)));
    else if (entry.name.endsWith('.mdx') || entry.name.endsWith('.md')) out.push(path);
  }
  return out;
}

/** Check one axis's version list. These are invariants other code relies on. */
function checkVersionList(axis: VersionAxis): string[] {
  const errors: string[] = [];
  const versions = axis.versions;

  const stable = versions.filter((v) => v.stable);
  if (stable.length !== 1) {
    errors.push(
      `exactly one entry must be \`stable\`, found ${stable.length}` +
        (stable.length ? ` (${stable.map((v) => v.label).join(', ')})` : ''),
    );
  }

  for (const key of ['label', 'value'] as const) {
    const seen = new Map<string, number>();
    for (const v of versions) seen.set(v[key], (seen.get(v[key]) ?? 0) + 1);
    for (const [val, n] of seen) {
      if (n > 1) errors.push(`duplicate ${key} "${val}" (${n} entries)`);
    }
  }

  for (const v of versions) {
    if (!VERSION_RE.test(v.value)) {
      errors.push(`value "${v.value}" is not a bare version (no "v", no range)`);
    }
    // The dropdown writes `label` into `?v=`, and `resolveVersion` maps it
    // back by comparing against `value`. A label that does not resolve to its
    // own entry would select a different doc-state than the reader clicked.
    if (VERSION_RE.test(v.label) && compareVersions(v.label, v.value) !== 0) {
      errors.push(
        `label "${v.label}" does not compare equal to value "${v.value}", so selecting it would resolve to another doc-state`,
      );
    }
  }

  return errors;
}

/** Validate the markers found in one file against the version list for `axis` (or "no axis"). */
function checkFileMarkers(
  file: string,
  body: string,
  axis: VersionAxis | null,
): { problems: Problem[]; total: number } {
  const lineAt = (index: number) => body.slice(0, index).split('\n').length;
  const known = new Set((axis?.versions ?? []).map((v) => v.value));
  const oldest = axis ? versionsNewestFirst(axis).at(-1) : undefined;

  const problems: Problem[] = [];
  let total = 0;

  for (const { what, re } of MARKERS) {
    for (const m of body.matchAll(re)) {
      const version = m[1];
      // The authoring template in the cli.mdx maintainer note uses literal
      // placeholders; skip them rather than making the note un-writable.
      if (version.includes('x.y.z')) continue;
      total++;

      let reason = '';
      if (!axis) {
        reason = 'this page has no registered version axis (src/lib/version-axes.ts), so no doc-state can apply here';
      } else if (!VERSION_RE.test(version)) {
        reason = 'not a bare version (no "v", no range)';
      } else if (!known.has(version)) {
        reason = known.size
          ? `not a declared doc-state for "${axis.label}" (have ${[...known].join(', ')})`
          : 'no doc-states declared for this axis';
      } else if (oldest && compareVersions(version, oldest.value) <= 0) {
        // A `since` at or below the oldest doc-state is never hidden by any
        // selection, so the gate is inert and the marker is misleading.
        reason = `at or below the oldest doc-state (${oldest.value}), so the gate can never hide anything`;
      }

      if (reason) {
        problems.push({ file: relative('.', file), line: lineAt(m.index ?? 0), what, version, reason });
      }
    }
  }

  return { problems, total };
}

async function main(): Promise<void> {
  console.log(`🔍 Checking version gates against ${VERSION_AXES.length} registered axes...\n`);

  const listErrors = new Map<string, string[]>();
  for (const axis of VERSION_AXES) {
    const errors = checkVersionList(axis);
    if (errors.length > 0) listErrors.set(axis.key, errors);
  }

  const files = await findMdx(CONTENT_DIR);
  const problems: Problem[] = [];
  let total = 0;

  for (const file of files) {
    const body = await readFile(file, 'utf-8');
    const axis = getVersionAxis(fileToSlug(file));
    const result = checkFileMarkers(file, body, axis);
    problems.push(...result.problems);
    total += result.total;
  }

  const stateCounts = VERSION_AXES.map((a) => `${a.key}: ${a.versions.length}`).join(', ');
  console.log(`Checked ${total} version marker(s) across ${files.length} files, against [${stateCounts}]\n`);

  if (listErrors.size === 0 && problems.length === 0) {
    console.log('✅ All version gates reference a declared doc-state on their own axis.');
    return;
  }

  for (const [key, errors] of listErrors) {
    const source = key === 'pear' ? 'src/lib/docs-versions.ts' : `src/lib/${key}-docs-states.json`;
    console.error(`❌ ${key} axis (${source}):`);
    for (const e of errors) console.error(`   ${e}`);
    console.error('');
  }

  if (problems.length > 0) {
    console.error(`❌ ${problems.length} bad version marker(s):\n`);
    for (const p of problems) {
      console.error(`   ${p.file}:${p.line}`);
      console.error(`     ${p.what} "${p.version}" — ${p.reason}`);
    }
    console.error(
      '\n   Add the release to the relevant axis in src/lib/version-axes.ts (or regenerate it), or correct the marker.',
    );
  }

  process.exitCode = 1;
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
