// scripts/refgen/render.ts
//
// Render a combined reference page: the upstream README's narrative sections
// (Install, Prerequisites, Usage, Workflows, …) kept verbatim, followed by the
// generated API reference built from the api-model. This is the "combine" output
// — hand-written setup prose + machine-generated, source-accurate API surface.
//
// Output is Markdown/MDX-compatible. It is emitted as a committed artifact under
// generated/refs/<slug>/ — it does not overwrite the curated pages in content/.
//
// Render filter: by default only README-backed members are shown, so the page
// reads like a hand-authored one. AST-only members (internal fields, inherited
// boilerplate like `emit`/`once`) stay in the model for parity and are listed in
// the improvement plan; pass `full` to render every member inline.

import type { ApiModel, RefClass, RefMethod } from './model';

export interface RenderOptions {
  /** Render every member, including AST-only ones not documented upstream. */
  full?: boolean;
}

/** A member shows on the page when documented upstream (or in full mode). */
function isDocumented(m: RefMethod): boolean {
  return m.source.includes('readme');
}

/** Mechanical grouping of methods into reference sub-sections. */
const GROUPS: { title: string; match: (m: RefMethod) => boolean }[] = [
  { title: 'Constructor', match: (m) => m.kind === 'constructor' },
  { title: 'Static helpers', match: (m) => m.static && m.kind !== 'constructor' },
  { title: 'Methods', match: (m) => !m.static && (m.kind === 'method') },
  { title: 'Properties', match: (m) => !m.static && (m.kind === 'getter' || m.kind === 'setter' || m.kind === 'property') },
  { title: 'Events', match: (m) => m.kind === 'event' },
];

function frontmatter(model: ApiModel): string {
  const title = model.classes[0]?.name ?? model.slug;
  const description = (model.description ?? `${title} API reference.`).replace(/"/g, '\\"');
  return [
    '---',
    `title: "${title}"`,
    `description: "${description}"`,
    'docType: reference',
    'schemaType: APIReference',
    '---',
  ].join('\n');
}

function renderMethod(m: RefMethod): string {
  const lines: string[] = [`#### \`${m.signature}\``, ''];
  if (m.description) lines.push(m.description, '');

  const documented = m.params.filter((p) => p.description);
  if (documented.length > 0) {
    lines.push('**Parameters:**', '');
    for (const p of documented) {
      const opt = p.optional ? ' _(optional)_' : '';
      lines.push(`- \`${p.name}\`${opt} — ${p.description}`);
    }
    lines.push('');
  }

  if (m.returns) lines.push(`**Returns:** ${m.returns.replace(/^returns\s*/i, '')}`, '');
  if (m.sourceLink) lines.push(`[Source](${m.sourceLink})`, '');

  for (const ex of m.examples) lines.push('```js', ex, '```', '');

  return lines.join('\n').trimEnd();
}

function renderClass(cls: RefClass, heading: string, full: boolean): string {
  const shown = full ? cls.methods : cls.methods.filter(isDocumented);
  if (shown.length === 0) return '';

  const out: string[] = [heading, ''];
  for (const group of GROUPS) {
    const members = shown.filter(group.match);
    if (members.length === 0) continue;
    out.push(`### ${group.title}`, '');
    for (const m of members) out.push(renderMethod(m), '');
  }
  return out.join('\n');
}

/**
 * The API portion only: `## API Reference` + main-class groups, then each
 * sub-object class under its own `## <Class>`. No frontmatter, no narrative.
 * Used to assemble the standalone generated/refs/<slug>/reference.mdx artifact;
 * the curated content/reference pages are never overwritten with it (they are
 * richer — see scripts/refgen/sync.ts).
 */
export function renderApiBlock(model: ApiModel, options: RenderOptions = {}): string {
  const full = !!options.full;
  const parts: string[] = [];

  let omitted = 0;
  model.classes.forEach((cls, i) => {
    if (!full) omitted += cls.methods.filter((m) => !isDocumented(m)).length;
    const block = renderClass(cls, i === 0 ? '## API Reference' : `## ${cls.name}`, full);
    if (block) parts.push(block, '');
  });

  if (!full && omitted > 0) {
    parts.push(
      `{/* ${omitted} member(s) found in source but not documented upstream are omitted; see the improvement plan. Re-run with --full to include them. */}`,
      ''
    );
  }

  return parts.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd();
}

export function renderReference(model: ApiModel, options: RenderOptions = {}): string {
  const parts: string[] = [
    frontmatter(model),
    '',
    `{/* Generated by scripts/generate-refs.ts from ${model.repo.org}/${model.repo.repo}@${model.tag} (${model.sha.slice(0, 10)}). Do not edit by hand. */}`,
    '',
  ];

  // Narrative sections, verbatim and in README order.
  for (const section of model.sections) {
    parts.push(section.markdown, '');
  }

  parts.push(renderApiBlock(model, options), '');

  return parts.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}
